### ISSUE TITLE
v3.3.2 call to undefined function resolve with Lumen

### ISSUE THREAD

**Issue by samarqhand** [SocialiteProviders/Manager#130]
v3.3.1 works with my Lumen project, but if I upgrade to 3.3.2 it breaks. I am using the Azure provider, and when the user is redirected back to my site with the access token I get the error.

		Call to undefined function SocialiteProviders\\Manager\\resolve()
		vendor\\socialiteproviders\\manager\\src\\SocialiteWasCalled.php line 153

the code at that point is

        try {
            return resolve(ConfigRetrieverInterface::class)->fromServices(
                $providerName, $providerClass::additionalConfigKeys()
            );
        } catch (MissingConfigException $e) {
            throw new MissingConfigException($e->getMessage());
        }
		
I can't find a resolve function anywhere, where is it meant to be defined?

I am using composer to manage dependencies and can reliably switch between 3.3.1 and 3.3.2 to fix / break this.

thanks : )

**Comment by MKiselev** [comment]
Hello, I have same error with lumen and using custom providers(socialiteproviders/vkontakte, jhaoda/socialite-odnoklassniki).

`resolve` function is a Laravel helper defined at: https://github.com/laravel/framework/blob/5.7/src/Illuminate/Foundation/helpers.php#L764-L775 and it's just alias for `app` helper :)

@samarqhand thank you for bug report :)

This issue fixed by https://github.com/SocialiteProviders/Manager/commit/58b72a667da292a1d0a0b1e6e9aeda4053617030#diff-2bf83507afb73808379e3c6f150b62b7L153

@m1guelpf when you can you made release?

P.S.
In my Lumen project I added into `composer.json` into section `autoload` new key `files` for aitoload my helpers file:
```
"autoload": {
    "psr-4": {
        "App\\": "app/"
    },
    "files": [
        "bootstrap/helpers.php"
    ]
},
```

In helpers file I put some helpers, which use some packages, but doesn't have Lumen.
