### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by mrgodhani** [SocialiteProviders/Manager#20]
Getting following below error:

```
[ErrorException]
  Argument 3 passed to SocialiteProviders\Manager\SocialiteWasCalled::buildOAuth2Provider() must be of the type array, null given, called in /Users/meetgodhani/Desktop/Crowdlinker/picstats_api/vendor
  /socialiteproviders/manager/src/SocialiteWasCalled.php on line 59 and defined
```

**Comment by ahuggins** [comment]
Were you able to solve this? I am having the same issue

**Comment by DraperStudio** [comment]
Argument 3 is the config array, so make sure you created provider config in the `services.php` and placed the right name in your provider classes.

**Comment by ahuggins** [comment]
yeah...hmmm, I have checked that...I think the issue is "reloading" the page once you get the "whatever" driver is not found. If you get that setup, then just refresh the page, it seems like that causes the issue. I went back to a normal page, then tried the login/paypal (or live (microsoft)) and this Argument 3 issue seemed to correct itself. Now it seems to be working just fine. Thank you!
