### ISSUE TITLE
v2.1.8 no longer passes client_id

### ISSUE THREAD

**Issue by Strexm** [SocialiteProviders/Manager#64]
For both YouTube and Twitch at least, the 2.1.8 branch (from 2.1.5) no longer passes the client_id parameter, rendering a bad request.

`config/services` file looks as follows:

```
'youtube' => [
        'client_id'     => env('GOOGLE_CLIENT_ID'),
        'client_secret' => env('GOOGLE_CLIENT_SECRET'),
        'api_key'       => env('YOUTUBE_API_KEY'),
        'redirect'      => env('YOUTUBE_REDIRECT_URL'),
],
```

Performing `dd(env('GOOGLE_CLIENT_ID'))` displays the expected ID.

**Comment by DraperStudio** [comment]
I have removed the v2.1.8 release for now so you should be able to use the Providers as usual again.

**Comment by DraperStudio** [comment]
https://github.com/SocialiteProviders/Manager/releases/tag/v2.1.8

**Comment by Swanty** [comment]
Re-tagging after tag has already been pushed to remote should never be done.
People who already fetched the tag before re-tagging are having issues now (including me), since the tag is the same we won't get the re-tagged changes unless we manually delete and reinstall the package.

Please release a new version.
